name: Compile & Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['16']

    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: Queue
          path: target/Queue-*.jar
          if-no-files-found: error